### ISSUE TITLE
Unhandled promise rejection in get value()

### ISSUE THREAD

**Issue by jjdonov** [hupe1980/aws-parameter-cache#6]
Hi there! 👋 

First of all, thanks for making this!

I ran into an unhandled promise rejection when using your library. In this case, my environment is missing the AWS region however I think this issue would arise for any failure of the request.

```
node:29164) UnhandledPromiseRejectionWarning: ConfigError: Missing region in config
    at Request.VALIDATE_REGION (<redacted>/node_modules/aws-sdk/lib/event_listeners.js:92:45)
    at Request.callListeners (<redacted>/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (<redacted>/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at <redacted>/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (<redacted>/node_modules/aws-sdk/lib/config.js:379:7)
    at <redacted>/node_modules/aws-sdk/lib/config.js:397:9
    at SharedIniFileCredentials.get (<redacted>/node_modules/aws-sdk/lib/credentials.js:127:7)
    at getAsyncCredentials (<redacted>/node_modules/aws-sdk/lib/config.js:391:24)
    at Config.getCredentials (<redacted>/node_modules/aws-sdk/lib/config.js:411:9)
    at Request.VALIDATE_CREDENTIALS (<redacted>/node_modules/aws-sdk/lib/event_listeners.js:81:26)
    at Request.callListeners (<redacted>/node_modules/aws-sdk/lib/sequential_executor.js:102:18)
    at Request.emit (<redacted>/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (<redacted>/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (<redacted>/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (<redacted>/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at Request.runTo (<redacted>/node_modules/aws-sdk/lib/request.js:403:15)
    at <redacted>/node_modules/aws-sdk/lib/request.js:792:12
    at new Promise (<anonymous>)
    at Request.promise (<redacted>/node_modules/aws-sdk/lib/request.js:778:12)
    at Parameter.getParameter (<redacted>/node_modules/aws-parameter-cache/lib/parameter.js:35:52)
    at Parameter.refreshParameter (<redacted>/node_modules/aws-parameter-cache/lib/parameter.js:28:34)
    at Parameter.refresh (<redacted>/node_modules/aws-parameter-cache/lib/refreshable.js:8:14)
    at Parameter.get value [as value] (<redacted>/node_modules/aws-parameter-cache/lib/parameter.js:14:18)
```

[Adding a `.catch()` to the `cachedResult` promise should do the trick](https://github.com/hupe1980/aws-parameter-cache/blob/9ee51e7a897f368f43c7fa3e4dfe0f46931117e4/src/parameter.ts#L40). Inside that block we can call the wrapping promise's reject. I'd be happy to open a PR, but thought it'd be good to touch base first 😄 Let me know what you think!

**Comment by hupe1980** [comment]
@jjdonov Yes we should catch that. You are welcome to create a PR
